/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/layout/header.vue')['default']
    Modal: typeof import('./src/components/ui/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/ui/Search.vue')['default']
    User: typeof import('./src/components/user/User.vue')['default']
    UserCreate: typeof import('./src/components/user/UserCreate.vue')['default']
    UserDetails: typeof import('./src/components/user/UserDetails.vue')['default']
    Users: typeof import('./src/components/user/Users.vue')['default']
  }
}
